"""add pagamentos e cobranca meses

Revision ID: 41b642c99632
Revises: ec9150df9474
Create Date: 2026-01-10 16:26:46.811573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b642c99632'
down_revision: Union[str, Sequence[str], None] = 'ec9150df9474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liga_cobranca_meses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liga_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('mes >= 1 AND mes <= 12', name='ck_liga_cobranca_mes_range'),
    sa.ForeignKeyConstraint(['liga_id'], ['ligas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('liga_id', 'ano', 'mes', name='uq_liga_cobranca_mes')
    )
    with op.batch_alter_table('liga_cobranca_meses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liga_cobranca_meses_ano'), ['ano'], unique=False)
        batch_op.create_index(batch_op.f('ix_liga_cobranca_meses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liga_cobranca_meses_liga_id'), ['liga_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liga_cobranca_meses_mes'), ['mes'], unique=False)

    op.create_table('liga_pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liga_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('pago', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('mes >= 1 AND mes <= 12', name='ck_liga_pagamento_mes_range'),
    sa.ForeignKeyConstraint(['liga_id'], ['ligas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('liga_id', 'usuario_id', 'ano', 'mes', name='uq_liga_pagamento')
    )
    with op.batch_alter_table('liga_pagamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liga_pagamentos_ano'), ['ano'], unique=False)
        batch_op.create_index(batch_op.f('ix_liga_pagamentos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liga_pagamentos_liga_id'), ['liga_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liga_pagamentos_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_liga_pagamentos_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liga_pagamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liga_pagamentos_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_liga_pagamentos_mes'))
        batch_op.drop_index(batch_op.f('ix_liga_pagamentos_liga_id'))
        batch_op.drop_index(batch_op.f('ix_liga_pagamentos_id'))
        batch_op.drop_index(batch_op.f('ix_liga_pagamentos_ano'))

    op.drop_table('liga_pagamentos')
    with op.batch_alter_table('liga_cobranca_meses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liga_cobranca_meses_mes'))
        batch_op.drop_index(batch_op.f('ix_liga_cobranca_meses_liga_id'))
        batch_op.drop_index(batch_op.f('ix_liga_cobranca_meses_id'))
        batch_op.drop_index(batch_op.f('ix_liga_cobranca_meses_ano'))

    op.drop_table('liga_cobranca_meses')
    # ### end Alembic commands ###
