"""init schema

Revision ID: b059cf70a011
Revises: 
Create Date: 2025-12-17 19:00:13.676039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b059cf70a011'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('pais', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('jogos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temporada', sa.Integer(), nullable=False),
    sa.Column('rodada', sa.Integer(), nullable=False),
    sa.Column('time_casa', sa.String(), nullable=False),
    sa.Column('time_fora', sa.String(), nullable=False),
    sa.Column('gols_casa', sa.Integer(), nullable=True),
    sa.Column('gols_fora', sa.Integer(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('temporada', 'rodada', 'time_casa', 'time_fora', name='uq_jogo_temporada_rodada_times')
    )
    with op.batch_alter_table('jogos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jogos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jogos_rodada'), ['rodada'], unique=False)
        batch_op.create_index(batch_op.f('ix_jogos_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jogos_temporada'), ['temporada'], unique=False)
        batch_op.create_index(batch_op.f('ix_jogos_time_casa'), ['time_casa'], unique=False)
        batch_op.create_index(batch_op.f('ix_jogos_time_fora'), ['time_fora'], unique=False)

    op.create_table('times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=True),
    sa.Column('escudo_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('times', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_times_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_times_nome'), ['nome'], unique=True)
        batch_op.create_index(batch_op.f('ix_times_sigla'), ['sigla'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email_login', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('funcao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email_login'), ['email_login'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)

    op.create_table('ligas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('temporada', sa.Integer(), nullable=False),
    sa.Column('codigo_convite', sa.String(), nullable=False),
    sa.Column('id_dono', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_dono'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_convite', name='uq_liga_codigo_convite'),
    sa.UniqueConstraint('id_dono', 'temporada', 'nome', name='uq_liga_dono_temporada_nome')
    )
    with op.batch_alter_table('ligas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ligas_codigo_convite'), ['codigo_convite'], unique=True)
        batch_op.create_index(batch_op.f('ix_ligas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ligas_id_dono'), ['id_dono'], unique=False)
        batch_op.create_index(batch_op.f('ix_ligas_temporada'), ['temporada'], unique=False)

    op.create_table('temporadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competicao_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['competicao_id'], ['competicoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competicao_id', 'ano', name='uq_temporada_competicao_ano')
    )
    op.create_table('liga_membros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liga_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.Enum('dono', 'admin_liga', 'membro', name='liga_role_enum'), nullable=False),
    sa.Column('data_ingresso', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['liga_id'], ['ligas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('liga_id', 'usuario_id', name='uq_liga_membro_liga_usuario')
    )
    with op.batch_alter_table('liga_membros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liga_membros_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liga_membros_liga_id'), ['liga_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liga_membros_papel'), ['papel'], unique=False)
        batch_op.create_index(batch_op.f('ix_liga_membros_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('palpites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liga_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('jogo_id', sa.Integer(), nullable=False),
    sa.Column('placar_casa', sa.Integer(), nullable=False),
    sa.Column('placar_fora', sa.Integer(), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('ultima_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['jogo_id'], ['jogos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['liga_id'], ['ligas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('liga_id', 'usuario_id', 'jogo_id', name='uq_palpite_liga_usuario_jogo')
    )
    with op.batch_alter_table('palpites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_palpites_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_palpites_jogo_id'), ['jogo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_palpites_liga_id'), ['liga_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_palpites_pontos'), ['pontos'], unique=False)
        batch_op.create_index(batch_op.f('ix_palpites_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('palpites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_palpites_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_palpites_pontos'))
        batch_op.drop_index(batch_op.f('ix_palpites_liga_id'))
        batch_op.drop_index(batch_op.f('ix_palpites_jogo_id'))
        batch_op.drop_index(batch_op.f('ix_palpites_id'))

    op.drop_table('palpites')
    with op.batch_alter_table('liga_membros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liga_membros_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_liga_membros_papel'))
        batch_op.drop_index(batch_op.f('ix_liga_membros_liga_id'))
        batch_op.drop_index(batch_op.f('ix_liga_membros_id'))

    op.drop_table('liga_membros')
    op.drop_table('temporadas')
    with op.batch_alter_table('ligas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ligas_temporada'))
        batch_op.drop_index(batch_op.f('ix_ligas_id_dono'))
        batch_op.drop_index(batch_op.f('ix_ligas_id'))
        batch_op.drop_index(batch_op.f('ix_ligas_codigo_convite'))

    op.drop_table('ligas')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email_login'))

    op.drop_table('usuarios')
    with op.batch_alter_table('times', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_times_sigla'))
        batch_op.drop_index(batch_op.f('ix_times_nome'))
        batch_op.drop_index(batch_op.f('ix_times_id'))

    op.drop_table('times')
    with op.batch_alter_table('jogos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jogos_time_fora'))
        batch_op.drop_index(batch_op.f('ix_jogos_time_casa'))
        batch_op.drop_index(batch_op.f('ix_jogos_temporada'))
        batch_op.drop_index(batch_op.f('ix_jogos_status'))
        batch_op.drop_index(batch_op.f('ix_jogos_rodada'))
        batch_op.drop_index(batch_op.f('ix_jogos_id'))

    op.drop_table('jogos')
    op.drop_table('competicoes')
    # ### end Alembic commands ###
