"""push alerts log per liga

Revision ID: bce314ffc011
Revises: aa6894050f61
Create Date: 2026-01-12 17:23:49.709992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce314ffc011'
down_revision: Union[str, Sequence[str], None] = 'aa6894050f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    insp = sa.inspect(bind)

    if "push_alerts_log" not in insp.get_table_names():
        op.create_table(
            "push_alerts_log",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("jogo_id", sa.Integer(), nullable=False),
            sa.Column("liga_id", sa.Integer(), nullable=False),
            sa.Column("alert_type", sa.String(), nullable=False),
            sa.Column("sent_at", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("jogo_id", "liga_id", "alert_type", name="uq_push_alert_jogo_liga_tipo"),
        )

        with op.batch_alter_table("push_alerts_log", schema=None) as batch_op:
            batch_op.create_index("ix_push_alerts_log_jogo_id", ["jogo_id"], unique=False)
            batch_op.create_index("ix_push_alerts_log_liga_id", ["liga_id"], unique=False)

    # (se tiver outras alterações nessa migration, elas ficam fora do if)


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liga_pagamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liga_pagamentos_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_liga_pagamentos_mes'))
        batch_op.drop_index(batch_op.f('ix_liga_pagamentos_liga_id'))
        batch_op.drop_index(batch_op.f('ix_liga_pagamentos_id'))

    with op.batch_alter_table('liga_cobranca_meses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liga_cobranca_meses_mes'))
        batch_op.drop_index(batch_op.f('ix_liga_cobranca_meses_liga_id'))
        batch_op.drop_index(batch_op.f('ix_liga_cobranca_meses_id'))

    with op.batch_alter_table('push_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_push_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_push_tokens_id'))

    op.drop_table('push_tokens')
    with op.batch_alter_table('push_alerts_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_alerts_log_liga_id'))
        batch_op.drop_index(batch_op.f('ix_push_alerts_log_jogo_id'))

    op.drop_table('push_alerts_log')
    # ### end Alembic commands ###
