"""add jogo with fks

Revision ID: dd693f341cd2
Revises: b059cf70a011
Create Date: 2025-12-18 11:45:02.831855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd693f341cd2'
down_revision: Union[str, Sequence[str], None] = 'b059cf70a011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporada_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('time_casa_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('time_fora_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_jogos_temporada'))
        batch_op.drop_index(batch_op.f('ix_jogos_time_casa'))
        batch_op.drop_index(batch_op.f('ix_jogos_time_fora'))
        batch_op.drop_constraint(batch_op.f('uq_jogo_temporada_rodada_times'), type_='unique')
        batch_op.create_unique_constraint('uq_jogo_temporada_rodada_times', ['temporada_id', 'rodada', 'time_casa_id', 'time_fora_id'])
        batch_op.create_index(batch_op.f('ix_jogos_temporada_id'), ['temporada_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jogos_time_casa_id'), ['time_casa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jogos_time_fora_id'), ['time_fora_id'], unique=False)
        batch_op.create_foreign_key("fk_jogos_time_fora_id_times", 'times', ['time_fora_id'], ['id'])
        batch_op.create_foreign_key("fk_jogos_temporada_id_temporadas", 'temporadas', ['temporada_id'], ['id'])
        batch_op.create_foreign_key("fk_jogos_time_casa_id_times", 'times', ['time_casa_id'], ['id'])
        batch_op.drop_column('time_casa')
        batch_op.drop_column('time_fora')
        batch_op.drop_column('temporada')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporada', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('time_fora', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('time_casa', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jogos_time_fora_id'))
        batch_op.drop_index(batch_op.f('ix_jogos_time_casa_id'))
        batch_op.drop_index(batch_op.f('ix_jogos_temporada_id'))
        batch_op.drop_constraint('uq_jogo_temporada_rodada_times', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_jogo_temporada_rodada_times'), ['temporada', 'rodada', 'time_casa', 'time_fora'])
        batch_op.create_index(batch_op.f('ix_jogos_time_fora'), ['time_fora'], unique=False)
        batch_op.create_index(batch_op.f('ix_jogos_time_casa'), ['time_casa'], unique=False)
        batch_op.create_index(batch_op.f('ix_jogos_temporada'), ['temporada'], unique=False)
        batch_op.drop_column('time_fora_id')
        batch_op.drop_column('time_casa_id')
        batch_op.drop_column('temporada_id')

    # ### end Alembic commands ###
